

export const GET_DETAIL_ASYNC = 'GET_DETAIL_ASYNC';
export const GET_DETAIL = 'GET_DETAIL'; // 获取商品详情
export const ADD_ADDRESS_ASYNC = 'ADD_ADDRESS_ASYNC';
export const GET_ADDRESS = 'GET_ADDRESS';
export const DELETE_ADDRESS='DELETE_ADDRESS'; //删除某地址
export const GET_ORDERLIST = 'GET_ORDERLIST';
export const DELETE_ORDERLIST='DELETE_ORDERLIST'
export const ADD_ORDER_ASYNC = 'ADD_ORDER_ASYNC';
export const REMOVE_GOOD_ASYNC='REMOVE_GOOD_ASYNC'; // 下架商品
export const CHANGE_ORDER_ASYNC='CHANGE_ORDER_ASYNC'; // 改变order的status
export const POST_UPDATE_ASYNC = 'POST_UPDATE_ASYNC';
